"""add AIReview model

Revision ID: ab5e4aa1103e
Revises: 152550954606
Create Date: 2026-08-05 10:25:19.676191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ab5e4aa1103e'
down_revision: Union[str, Sequence[str], None] = '152550954606'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('repository_name', sa.String(), nullable=False),
    sa.Column('owner', sa.String(), nullable=False),
    sa.Column('pull_request_number', sa.Integer(), nullable=False),
    sa.Column('review_status', sa.String(), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('review_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_reviews_id'), 'ai_reviews', ['id'], unique=False)
    op.create_index(op.f('ix_ai_reviews_owner'), 'ai_reviews', ['owner'], unique=False)
    op.create_index(op.f('ix_ai_reviews_pull_request_number'), 'ai_reviews', ['pull_request_number'], unique=False)
    op.create_index(op.f('ix_ai_reviews_repository_name'), 'ai_reviews', ['repository_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_reviews_repository_name'), table_name='ai_reviews')
    op.drop_index(op.f('ix_ai_reviews_pull_request_number'), table_name='ai_reviews')
    op.drop_index(op.f('ix_ai_reviews_owner'), table_name='ai_reviews')
    op.drop_index(op.f('ix_ai_reviews_id'), table_name='ai_reviews')
    op.drop_table('ai_reviews')
    # ### end Alembic commands ###
