"""add_jti_to_refresh_tokens

Revision ID: e7b6c5d4a3b2
Revises: d5a540286adc
Create Date: 2026-08-07 09:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7b6c5d4a3b2'
down_revision = 'ab5e4aa1103e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('jti', sa.String(), nullable=True))
    op.create_index(op.f('ix_refresh_tokens_jti'), 'refresh_tokens', ['jti'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_tokens_jti'), table_name='refresh_tokens')
    op.drop_column('refresh_tokens', 'jti')
    # ### end Alembic commands ###
